language: python
python:
    - 2.7.8
    - 3.3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE _MysqlRoles;'
  - mysql -e "grant all on *.* to 'travis'@'127.0.0.1';"
  - mysql -e "grant all on *.* to 'travis'@'localhost';"

install:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script:
    - py.test MysqlRoles/tests/test_roleserv_fcns.py
    - py.test MysqlRoles/tests/test_rolemanage_fcns.py
