language: python
python:
    - 2.7.8
    - 3.3

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE _MysqlRoles;'
  - mysql -u root -e "grant all on *.* to 'travis'@'127.0.0.1' with grant option;"
  - mysql -u root -e "grant all on *.* to 'travis'@'localhost' with grant option;"

install:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script:
    - python -m MysqlRoles init 127.0.0.1
    - python -m MysqlRoles seed 127.0.0.1
    - python -m MysqlRoles update 127.0.0.1
