language: python
python:
    - 2.7.8
    - 3.3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE _MysqlRoles;'
  - mysql _MysqlRoles < create/table_create.sql
  - mysql _MysqlRoles < create/seed.sql

install:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script:
    - py.test MysqlRoles/tests/test_default_inits.py
