# run_updates_msr.yml
---
- hosts: rbac_db_servers
  sudo: yes

  tasks:
  -name: ensure a stable MysqlRoles is installed
   pip:
      name: MysqlRoles
      version: 0.3.3

  -name: run the update
   command: python -m MysqlRoles update arg1 arg2
      args:
          central: sys-p1
          manage: localhost
